declare module 'vite'
declare module 'faker'
declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.svg'
declare module '*.gif'
declare module '*.webp'
declare module 'echarts/lib/echarts';
declare module 'echarts-for-react';