version: '2'

services:
  # mysql配置
  my-mysql:
    image: mysql:8.0
    container_name: test-mysql
    restart: always
#    networks:
#      - monito
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD:123456
    command:
      --default-authentication-plugin=mysql_native_password
      --lower_case_table_names=2
      --explicit_defaults_for_timestamp=true
    volumes:
      - "/Users/linchengzhe/mysqlData/data:/var/lib/mysql"
      - "/Users/linchengzhe/mysqlData/logs:/logs"
      - "/Users/linchengzhe/mysqlData/conf:/etc/mysql/conf.d"

  #redis 配置
  my-redis:
    image: redis:latest
    restart: always
    container_name: test-redis
#    networks:
#      - monito
    ports:
      - 6379:6379
    command: redis-server /etc/redis/redis.conf
    volumes:
      - "/Users/linchengzhe/redisData/conf:/etc/redis/redis.conf"

  # golang gin 后台
  my-gin:
    restart: always
    depends_on:
      - my-redis
      - my-mysql
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - my-mysql
      - my-redis
#    networks:
#      - monito
    ports:
      - "80:80"


#networks:
#  monito:



#      --character-set-server=utf8mb4
#      --collation-server=utf8mb4_general_ci
#      --max_allowed_packet=128M;






